services:
  db:
    container_name: postgres_container
    hostname: postgres_container
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - fastapi_server/.env
    networks:
      - web_network

  fastapi_server:
    container_name: fastapi_container
    build:
      context: ./fastapi_server
    ports:
      - "8000:8000"
    entrypoint: >
      sh -c "
        echo "Starting..."
        alembic upgrade head
        uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000
      "
    volumes:
      - ./fastapi_server:/fastapi_server
    depends_on:
      - db
    networks:
      - web_network


networks:
  web_network:
    name: web_network
