services:
  db:
    container_name: postgres_container
    hostname: postgres_container
    image: postgres:14
    restart: always
    ports:
      - "5433:5433"
    volumes:
      - ./docker_pg_data/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - web_network


  fastapi_server:
    container_name: fastapi_container
    build:
      context: ./fastapi_server
    ports:
      - "8000:8000"
    command: bash -c "uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000 --log-level debug"
    volumes:
      - ./fastapi_server:/fastapi_server    # used for live reloading of container to changes in app on local machine
    depends_on:
      - db
    networks:
      - web_network


networks:
  web_network:
    name: web_network
